baseURL: http://something-fresh.org/
languageCode: en-us
title: SAFE
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If  you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/safe_logo.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: SAFE Stack
    # Hero subtitle (optional)
    subtitle: An end-to-end, functional-first stack for cloud-ready web development that emphasizes type-safe programming.
    # Button text
    buttontext: Learn More
    # Where the main hero button links to
    buttonlink: "#learn-more"
    # Hero image (from static/images/___)
    image: illustrations/safe-stack.png
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - client: saturn
      url: https://saturnframework.org/
    - client: azure
      url: https://azure.microsoft.com/en-us/
    - client: fable
      url: https://fable.io/
    - client: elmish
      url: https://elmish.github.io/
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Docs
    url: https://safe-stack.github.io/docs/intro/
  - title: About
    url: https://www.compositional-it.com/news-blog/introducing-the-safe-stack/
  - title: Support
    url: https://safe-stack.github.io/docs/support/
  - title: SAFE Dojo
    url: https://github.com/CompositionalIT/SAFE-Dojo/
    button: true
  section1:
    title: What is SAFE?
    tiles:
    - icon: mouse-globe
      text: SAFE is an application development stack that brings several technologies together into a single, coherent stack for type-safe, flexible, web-enabled applications that can be written almost entirely in F#.
  section2:
    features:
    - title: Functional First
      text: Make use of F# throughout your application stack. No need to compromise by shoehorning your design into an OO framework - make use of functional-first constructs and ideas throughout your codebase in F#, even in the browser! Start taking advantage of F# features such as type providers, rich domain modelling and a safer type system today.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: functional-first
    - title: Skill Reuse
      text: Reuse your team's server-side development skills across the entire application stack. There's no need to become a Javascript or CSS expert - with tools and libraries such as Fable, Elmish and Fulma, you can create compelling, mobile-friendly web applications today.
      icon: skill-reuse
    - title: Code Sharing
      text: Seamlessly share F# between client and server. Create domain models that exist on client and server without having to worry about serialization, or create validation logic that can run in both browser and server - no need for expensive round trips for validation in the browser.
      icon: code-sharing
    - title: Rapid Development Cycle
      text: Get results - fast. With full support for .NET Core, including flexible cross platform templates, and cutting-edge features like hot module reloading and shared code you can start creating full-blown applications quicker than ever before.
      icon: rapid-cycle
#  section3:
#    title: One platform
#    subtitle: To rule them all
#    image: illustrations/mockups/app-mockup.png
#    buttonText: Get started
#    buttonLink: "#"
#  section4:
#    title: Our Clients love us!
#    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
#    clients:
#    - name: Irma Walters
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: Accountant
#      img: 1
#    - name: John Bradley
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: Financial Analyst
#      img: 2
#    - name: Gary Blackman
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: HR Manager
#      img: 3
#  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: safe_grayscale.png
    # Social Media Title
    socialmediatitle: Follow SAFE
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/SAFE-stack
      icon: github
    - link: https://twitter.com/safe_stack
      icon: twitter
#    bulmalogo: true
#    quicklinks:
#      column1:
#        title: "Product"
#        links:
#        - text: Discover features
#          link: /
#        - text: Why choose our product?
#          link: /
#        - text: Compare features
#          link: /
#        - text: Our roadmap
#          link: /
#        - text: AGB
#          link: /agb
#      column2:
#        title: "Docs"
#        links:
#        - text: Get started
#          link: /
#        - text: User guides
#          link: /
#        - text: Admin guide
#          link: /
#        - text: Developers
#          link: /
#      column3:
#        title: "Blog"
#        links:
#        - text: Latest news
#          link: /blog/first
#        - text: Tech articles
#          link: /blog/second
