baseURL: http://localhost:1313/
languageCode: en-us
title: SAFE
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If  you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: The best way to write functional-first web applications.
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/safe_logo.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: SAFE Stack
    # Hero subtitle (optional)
#    subtitle: 
    subtitle: The best way to write functional-first web applications.
    # Button text
    buttontext: Learn More
    # Where the main hero button links to
    buttonlink: "#benefits"
    # Hero image (from static/images/___)
    image: illustrations/safe-stack.png
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - client: cit
      url: https://www.compositional-it.com/
    - client: lambda
      url: https://lambdafactory.io/
    tiles:
      - title: Quick Start
        icon: mouse-globe
        text: Ready to get hands-on? It's quick and easy.
        url: https://safe-stack.github.io/docs/quickstart/
        buttonText: Get Up and Running
      - title: SAFE Dojo
        icon: laptop-cloud
        text: Learn SAFE by doing beginner-friendly challenges.
        url: https://github.com/CompositionalIT/SAFE-Dojo
        buttonText: Do the SAFE Dojo
      - title: Live Demo
        icon: plug-cloud
        text: See how it all comes together in production.
        url: https://safe-search-demo-web.azurewebsites.net/
        buttonText: View a Live Demo
  navbar:
  - title: About SAFE
    url: https://www.compositional-it.com/news-blog/introducing-the-safe-stack/
  - title: Get Support
    url: https://safe-stack.github.io/docs/support/
  - title: Read the Docs
    url: https://safe-stack.github.io/docs/intro/
    button: true
  section2:
    title: Why SAFE Stack?
    subtitle: SAFE Stack allows you to quickly develop compelling web applications that use industry-standard technologies whilst using F# to ensure an enjoyable development experience.
    features:
    - title: Productive
      text: Develop full stack web applications entirely in F#. Benefit from the power that F# and functional programming brings both on the server with .NET Core but also in the browser. Share types and functions seamlessly - no more manual mapping between browser and server languages!
      # Icon (from /images/illustrations/icons/___.svg)
      icon: productive
    - title: Fun
      text: SAFE Stack brings not only confidence to you but a sense of satisfaction and enjoyment to your development cycle. You'll be delighted with the ease at which you can create client-server web applications.
      icon: fun
    - title: Flexible
      text: SAFE Stack isn't a walled garden or closed ecosystem. It runs on top of existing ecosystems and tools including ASP .NET Core, .NET Core, Webpack, React and NPM. Using SAFE Stack means you can continue to use the libraries and tools that you already know and love, but still take advantage of the extra benefits that F# brings to the table!
      icon: flexible
    - title: A Safe Bet
      text: F# levels up the safety of your system without making you write reams of code. Gain more confidence that your code does what you expect it to do, with no dynamic typing required for the browser. And the SAFE Stack runs on trusted platforms such as ASP .NET, .NET Core, NPM and Webpack - popular, high-performance and reliable platforms with millions of users.
      icon: safety-first
  section3:
    title: SAFE Search
    subtitle: A property search demo built entirely with SAFE
    image: illustrations/mockups/safe-search.PNG
    buttonText: View Live
    buttonLink: https://safe-search-demo-web.azurewebsites.net/
  section4:
    title: Testimonials
#    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: MSU Solutions
      quote: We at msu solutions GmbH are big fans of SAFE stack. For the last couple of years we were already using F# open source technologies for web and mobile projects. Tools like the Fable compiler and elmish are rock solid and a pleasure to work with.
#      job: Accountant
      img: 1
    - name: Goswin Rothenthal
      quote: It just works! The docs are very detailed and helpful. I got the template up and running on a public URL on Azure within one hour. Without any issues. Even though I am new to dotnet core and Azure.
#      job: Financial Analyst
      img: 2
    - name: Demetrix
      quote: SAFE was the perfect place to start our biological design and data management platform. I would start with SAFE again in a heartbeat for a new project. We shared some of our experiences at Open F# 2018.
#      job: HR Manager
      img: 3
#  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: safe_grayscale.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/SAFE-stack
      icon: github
    - link: https://twitter.com/safe_stack
      icon: twitter
#    bulmalogo: true
#    quicklinks:
#      column1:
#        title: "Product"
#        links:
#        - text: Discover features
#          link: /
#        - text: Why choose our product?
#          link: /
#        - text: Compare features
#          link: /
#        - text: Our roadmap
#          link: /
#        - text: AGB
#          link: /agb
#      column2:
#        title: "Docs"
#        links:
#        - text: Get started
#          link: /
#        - text: User guides
#          link: /
#        - text: Admin guide
#          link: /
#        - text: Developers
#          link: /
#      column3:
#        title: "Blog"
#        links:
#        - text: Latest news
#          link: /blog/first
#        - text: Tech articles
#          link: /blog/second
